name: 'Run Dash Platform Test Suite'
description: 'Runs end-to-end and functional testing against a Dash network'
inputs:
  faucet-private-key:
    description: Faucet private key
  dpns-contract-id:
    description: DPNS contract ID
  dpns-top-level-identity-id:
    description: DPNS top level identity ID
  dpns-top-level-identity-private-key:
    description: DPNS top level identity private key
  sdk-install:
    description: SDK install
runs:
  using: 'docker'
  image: 'docker://dashpay/platform-test-suite'
  args:
    - 127.0.0.1:3000:3010
    - --network=regtest
    - --faucet-key=${{ inputs.faucet-private-key }}
    - --dpns-contract-id=${{ inputs.dpns-contract-id }}
    - --dpns-contract-block-height=${{ inputs.dpns-contract-block-height }}
    - --dpns-tld-identity-id=${{ inputs.dpns-top-level-identity-id }}
    - --dpns-tld-identity-private-key=${{ env.dpns-top-level-identity-private-key }}
    # - ${{ inputs.sdk-install }}
