name: 'Run Dash Platform Test Suite'
description: 'Runs end-to-end and functional testing against a Dash network'
inputs:
  current-version:
    description: Current version
    default:
  faucet-private-key:
    description: Faucet private key
    default:
  dpns-contract-id:
    description: DPNS contract ID
    default: ${env.dpns-contract-id}
  dpns-contract-block-height:
    description: DPNS contract block height
    default: ${env.dpns-contract-block-height}
  dpns-top-level-identity-id:
    description: DPNS top level identity ID
    default: --dpns-tld-identity-id=$DPNS_TOP_LEVEL_IDENTITY_ID 
  dpns-top-level-identity-private-key:
    description: DPNS top level identity private key
    default:
  sdk-install:
    description: SDK install
    default:
runs:
  using: 'docker'
  image: 'docker://dashpay/platform-test-suite'
  args:
    - 127.0.0.1:3000:3010
    - ${{ inputs.current-version }}
    - ${{ inputs.faucet-private-key }}
    - "--dpns-contract-id-1=${{ inputs.dpns-contract-id }}"
    - --dpns-contract-id-2=${env.dpns-contract-id}
    - "${{ inputs.dpns-contract-block-height }}"
    - "${inputs.dpns-contract-id}"
    - ${{ inputs.dpns-top-level-identity-id }}
    - ${{ inputs.dpns-top-level-identity-private-key }}
    - ${{ inputs.sdk-install }}
